# Generated by Django 5.2.3 on 2025-08-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("waiter", "Waiter"),
                    ("admin", "Admin/Manager"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
