# Generated by Django 5.2.3 on 2025-08-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dish", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="preparation",
            field=models.TextField(blank=True),
        ),
    ]
