# Generated by Django 5.2.3 on 2025-06-27 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("branch", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaffleWinner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raffle_name", models.CharField(max_length=100)),
                ("won_at", models.DateTimeField(auto_now_add=True)),
                ("prize_description", models.CharField(max_length=255)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="branch.branch",
                    ),
                ),
            ],
        ),
    ]
