# Generated by Django 5.2.3 on 2025-07-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fidelity_card", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fidelitycard",
            name="pointsRequired",
        ),
        migrations.AddField(
            model_name="fidelitycard",
            name="points_required",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
