# Generated by Django 5.2.3 on 2025-08-16 09:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fidelity_card", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fidelitycard",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="fidelitycard",
            name="issued_at",
        ),
        migrations.RemoveField(
            model_name="fidelitycard",
            name="points_required",
        ),
        migrations.AddField(
            model_name="fidelitycard",
            name="description",
            field=models.TextField(
                blank=True, help_text="Details of benefits for this card type"
            ),
        ),
        migrations.AddField(
            model_name="fidelitycard",
            name="duration_days",
            field=models.PositiveIntegerField(
                default=365, help_text="Duration in days before expiry"
            ),
        ),
        migrations.AddField(
            model_name="fidelitycard",
            name="monthly_order_requirement",
            field=models.PositiveIntegerField(
                default=0, help_text="Orders required per month"
            ),
        ),
        migrations.AddField(
            model_name="fidelitycard",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="fidelitycard",
            name="raffle_spots",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of raffle entries this card gives"
            ),
        ),
        migrations.AddField(
            model_name="fidelitycard",
            name="renewal_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="fidelitycard",
            name="six_month_points_requirement",
            field=models.PositiveIntegerField(
                default=0, help_text="Points required in 6 months"
            ),
        ),
        migrations.AlterField(
            model_name="fidelitycard",
            name="card_type",
            field=models.CharField(
                choices=[("bronze", "Bronze"), ("silver", "Silver"), ("gold", "Gold")],
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="fidelitycard",
            name="reward",
            field=models.CharField(
                blank=True, help_text="Gift given upon subscription", max_length=255
            ),
        ),
        migrations.CreateModel(
            name="FidelityCardSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "monthly_orders",
                    models.PositiveIntegerField(
                        default=0, help_text="Orders this month"
                    ),
                ),
                (
                    "six_month_points",
                    models.PositiveIntegerField(
                        default=0, help_text="Total points in last 6 months"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "fidelity_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="fidelity_card.fidelitycard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
