# Generated by Django 5.2.3 on 2025-07-28 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestorder",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="order.order",
            ),
        ),
    ]
