# Generated by Django 5.2.3 on 2025-07-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_guestorder_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("preparing", "Preparing"),
                    ("ready", "Ready"),
                    ("en_route", "En Route"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="table_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="type",
            field=models.CharField(
                choices=[
                    ("dine-in", "Dine-In"),
                    ("takeaway", "Takeaway"),
                    ("delivery", "Delivery"),
                ],
                default="old",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
