# Generated by Django 5.2.3 on 2025-07-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_order_notes_order_status_order_table_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="type",
            field=models.CharField(
                choices=[
                    ("dine-in", "Dine-In"),
                    ("takeaway", "Takeaway"),
                    ("delivery", "Delivery"),
                ],
                default="dine-in",
                max_length=20,
            ),
        ),
    ]
